jenkins:
    restart: always
    image: jenkins
    volumes:
        - ./jenkins_home/jobs:/var/jenkins_home/jobs
        - ./jenkins_home/config:/var/jenkins_home/config
        - ./jenkins_home/plugins:/var/jenkins_home/plugins
    ports:
        - 8080:8080
        - 50000:50000
